### PR TITLE
[Abandon] Add ssl_verify flag to the Jenkins class

### PR DESCRIPTION
**Pull request by ripcurld00d**
There are times when one doesn't want to verify the jenkins master certificate.
Although, this can be done by passing such a `requester`, IMHO it
will be hassle-free to use the `ssl_verify` parameter.

### CODE REVIEW

**Comment by ripcurld00d** [comment]
Hmm... I may have idea how to improve the code quality (too many argument)

**Comment by ripcurld00d** [comment]
Wow! Sorry for that! I just like automatically push small changes. I will work on modifying the unit-tests so it won't fail + updating the doc. till then...

**Comment by lechat** [comment]
This change makes ``jenkinsapi`` incompatible with previous version. I think that is is better to add one parameter and disable pylint check for this intead of introduction of completely new parameter, ``auth``.

I will not accept this pull request. What do you think, @salimfadhley ?

**Comment by ripcurld00d** [comment]
:+1: @lechat - I actually agree with you: adding `auth` parameter is a totally pain in the neck. That's why I separate it from the first commit. Anyway, I am going to revert that.

**Comment by ripcurld00d** [comment]
@lechat is there a way to run the tests again? i am not sure if the tests fail due to my changes.

**Comment by lechat** [comment]
The error caused by bug in Jenkins 1.602, as described in #340. This bug renders all job related API functions completely unusable.

**Pull request closed without merging**
