### PR TITLE
Fix usage of KrbRequester

### PR DESCRIPTION
**Pull request by pkocandr**

### CODE REVIEW

**Comment by pkocandr** [comment]
Re-requesting PR #320 with a test.

**Comment by lechat** [comment]
You need to add ``requests_kerberos`` to ``setup.py`` - this is external library and it needs to be installed.

**Comment by lechat** [comment]
It looks like ``requests_kerberos`` is not Python 3.x compatible...

**Comment by pkocandr** [comment]
Yes, seems like that. However it was used there before, we only realized now with the added test. Not sure what is the best approach now.

**Comment by lechat** [comment]
There were no direct dependency on that library and it was never checked under python 3.x 

Now there is...

I suggest that you remove dependency from setup.py, comment out the test, put comment into ``utils/krb_requester.py`` and add a paragraph into README.rst describing how to make Kerberos working.

**Comment by lechat** [comment]
As there is not activity on this for almost a year, I am closing this.

**Pull request closed without merging**
