### PR TITLE
Add a warnning message if fingerprints aren't enabled

### LINKED ISSUE #403: Why do I get this error message when I'm trying to save an artifact?
Hi guys,
I'm using the latest Jenkins 1.637 to create a software-project-building job for my company.
After the job finished, I use the tar tool to pack some libs into a tar.gz package and try to get it from user side via the 0.2.29 version of JenkinsAPI.
But I will get, for every time, an error message from the JenkinsAPI's Artifact.save() function:
"ERROR:root:Failed request at http://xxx.xxx.xxx.xxx:xxxxxx/fingerprint/xxxxxxxxxxxxxxxx/api/python with params: None"
Finally I can still find that the artifact has been saved to the path I specified.
Just curious why I always get this error mesasge.
Could someone please help me?

### PR DESCRIPTION
**Pull request by ripcurld00d**
Should close #403

### CODE REVIEW

**Comment by ripcurld00d** [comment]
ping @lechat feedback, please? :smiley_cat:

**Comment by salimfadhley** [comment]
It looks like some of the tests are failing - we cannot merge in this state. Would you kindly have another look at this proposed change?

**Comment by ripcurld00d** [comment]
Yeah, no problem.

**Comment by ripcurld00d** [comment]
I am reopening it due to @lechat's fix.

**Pull request closed without merging**
