### PR TITLE
Add ssl_verify flag to the Jenkins class

### PR DESCRIPTION
**Pull request by ripcurld00d**
There are times when one doesn't want to verify the jenkins master certificate.
Although, this can be done by passing such a requester, ssl_verify argument
will do the job and make the code more readable.

### CODE REVIEW

**Comment by ripcurld00d** [comment]
I have lost track of my old PR #387 so I have made a new one and ran the tests locally to make sure it passes.

Tested with Python 2.7.8 and 3.4.1

:pray:

**Comment by ripcurld00d** [comment]
I have lost track of my old PR #338 so I have made a new one and ran the tests locally to make sure it passes.

Tested with Python 2.7.8 and 3.4.1
:pray:

**Comment by salimfadhley** [comment]
One last detail - would you mind checking that your changes have not affected coverage. You ought to be able to see a coverage report via Travis, or just run it locally in your own development environment. The code change looks good - thank you for taking the time to make it neat. Future developers will thank you!

**Comment by ripcurld00d** [comment]
Hey @salimfadhley, are you talking about these lines?

    $ pep8 --ignore=E501 jenkinsapi/*.py
    The command "pep8 --ignore=E501 jenkinsapi/*.py" exited with 0.

    $ pylint --rcfile=pylintrc jenkinsapi/*.py --disable R0912
    Warning: option include-ids is deprecated and ignored.
    The command "pylint --rcfile=pylintrc jenkinsapi/*.py --disable R0912" exited with 0.

**Comment by salimfadhley** [comment]
I merged it anyway. PyLint is just a code-style checker (but not as good as Landscape). 

We do our coverage checking with Nosetests coverage plugin.

**Comment by ripcurld00d** [comment]
Thanks for merging.

    Name  Stmts Miss Cover Missing
    -------------------------------------------------------------------
    jenkinsapi.py 8 1 88% 69
    jenkinsapi/api.py 119 90 24% 31-34, 43-46, 55-58, 67-70, 78-88, 98-114, 125-131, 140-157, 167, 179-184, 192-213, 230-253
    jenkinsapi/artifact.py 63 6 90% 43, 57, 112-114, 131
    jenkinsapi/build.py 226 84 63% 28-30, 81, 95-101, 115-118, 122, 133, 157-158, 168, 177-178, 189, 206-212, 219-225, 232-239, 246-256, 263-273, 280-295, 317-318, 325, 346-347, 353-364, 370, 376, 415-418, 430
    jenkinsapi/command_line.py 0 0 100%
    jenkinsapi/config.py 2 0 100%
    jenkinsapi/constants.py 13 0 100%
    jenkinsapi/custom_exceptions.py 42 0 100%
    jenkinsapi/executor.py 24 0 100%
    jenkinsapi/executors.py 18 0 100%
    jenkinsapi/fingerprint.py 63 26 59% 68-69, 73-91, 94-104, 111-112
    jenkinsapi/jenkins.py 189 21 89% 11-14, 64-65, 73, 78-80, 87-89, 92-93, 169, 198, 205, 243, 246-247, 328
    jenkinsapi/jenkinsbase.py 76 9 88% 26, 38, 47, 49, 86-88, 94, 119
    jenkinsapi/job.py 342 82 76% 27-29, 191, 199, 227, 311-314, 332-333, 339-340, 359-360, 366-367, 377-384, 419-421, 429-433, 449, 453, 491-501, 514-524, 541-544, 550, 564-565, 573-579, 586-592, 603-604, 626-632, 657-658
    jenkinsapi/jobs.py 69 16 77% 26, 40-47, 71-76, 111-114, 160-161
    jenkinsapi/mutable_jenkins_thing.py 5 0 100%
    jenkinsapi/node.py 51 8 84% 11-13, 50, 53, 66, 75, 93, 120
    jenkinsapi/nodes.py 34 2 94% 56, 59
    jenkinsapi/plugin.py 10 0 100%
    jenkinsapi/plugins.py 39 0 100%
    jenkinsapi/queue.py 102 14 86% 46-47, 53, 63, 100, 119, 122, 126, 149-152, 163-164
    jenkinsapi/result.py 12 5 58% 16, 19-22
    jenkinsapi/result_set.py 32 9 72% 25, 35, 48-51, 54, 57-58
    jenkinsapi/utils.py 0 0 100%
    jenkinsapi/utils/requester.py 62 4 94% 8-10, 83-84
    jenkinsapi/view.py 101 10 90% 6-8, 61-63, 70, 73, 168, 192-195
    jenkinsapi/views.py 56 9 84% 28, 32, 45-46, 57-62
    -------------------------------------------------------------------
    TOTAL 1758 396 77%
    ----------------------------------------------------------------------
    Ran 203 tests in 444.369s
    OK

**Comment by ripcurld00d** [comment]
BTW, I have written a small [document](https://gist.github.com/ripcurld00d/01eaa3548cbffa816ed5) about this change.

**Comment by salimfadhley** [comment]
It might be worth adding that into the doc directory. Also add an example (with comments) that demonstrates how it all works. Also add your name to the list of authors in the readme file.

**Pull request merged**
