### PR TITLE
 jenkins.install_plugin, jenkins.install_plugins, and jenkins.safe_restart

### PR DESCRIPTION
**Pull request by mattvonrocketstein**
Just started working with the api and here are a few things I found missing.  Let me know if you like the look of these additions and if so I'll look into writing tests.

### CODE REVIEW

**Comment by lechat** [comment]
Hi,

Could you add unit or system tests for this new functions?

Thanks!

**Comment by mattvonrocketstein** [comment]
I prefer to write system tests, but I think that testing safe_restart() will be very time consuming for the test runner.  Is that a problem?

**Comment by salimfadhley** [comment]
Not as much of a problem as leaving it untested!

I expect the systest runner might need some rework to allow you to test a
restart - if that behavior kills the main process then it might get
confused.

**Comment by mattvonrocketstein** [comment]
Agreed, I just wasn't sure if the feeling might be that system tests are already way too slow.  I'm guessing safe-restart is sending HUP or something rather than killing the process, so hopefully my solution is working but of course it's not too straightforward for me to try it locally.

Meanwhile I've realized the plugin tests can't be system tests-- these would have to download something from external sources and I don't want to introduce intermittent build failures because of network issues, etc.  So now I've got unittests I think will work.  ~~how can I run the suite locally?~~ Nevermind, got it

**Comment by lechat** [comment]
Hi,

Don't be afraid of network issues, they rarely (if ever) occur on Travis. Our systests always download Jenkins, on every test and I never seen this failing.

If your local tests are too slow to always start Jenkins, you could start Jenkins instance and set JENKINS_URL environment variable - this variable tells tests that Jenkins is already running, so they will not try to download and start Jenkins. Of course, for safety reasons, that instance shall be new one, created specifically for testing purposes.

Hope this helps!

**Comment by mattvonrocketstein** [comment]
Finally!  Let me know if there's anything else blocking the merge.

**Pull request merged**
